// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: plot.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMSG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ClientMSG) Reset() {
	*x = ClientMSG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMSG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMSG) ProtoMessage() {}

func (x *ClientMSG) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMSG.ProtoReflect.Descriptor instead.
func (*ClientMSG) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMSG) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ClientMSG) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ClientSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientSignal) Reset() {
	*x = ClientSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSignal) ProtoMessage() {}

func (x *ClientSignal) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSignal.ProtoReflect.Descriptor instead.
func (*ClientSignal) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{1}
}

type ClientREQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*ClientREQ_Message
	//	*ClientREQ_Signal
	Request isClientREQ_Request `protobuf_oneof:"request"`
}

func (x *ClientREQ) Reset() {
	*x = ClientREQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientREQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientREQ) ProtoMessage() {}

func (x *ClientREQ) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientREQ.ProtoReflect.Descriptor instead.
func (*ClientREQ) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{2}
}

func (m *ClientREQ) GetRequest() isClientREQ_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ClientREQ) GetMessage() *ClientMSG {
	if x, ok := x.GetRequest().(*ClientREQ_Message); ok {
		return x.Message
	}
	return nil
}

func (x *ClientREQ) GetSignal() *ClientSignal {
	if x, ok := x.GetRequest().(*ClientREQ_Signal); ok {
		return x.Signal
	}
	return nil
}

type isClientREQ_Request interface {
	isClientREQ_Request()
}

type ClientREQ_Message struct {
	Message *ClientMSG `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ClientREQ_Signal struct {
	Signal *ClientSignal `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

func (*ClientREQ_Message) isClientREQ_Request() {}

func (*ClientREQ_Signal) isClientREQ_Request() {}

type ServerMSG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *ClientMSG `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Id  string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ServerMSG) Reset() {
	*x = ServerMSG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMSG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMSG) ProtoMessage() {}

func (x *ServerMSG) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMSG.ProtoReflect.Descriptor instead.
func (*ServerMSG) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMSG) GetMsg() *ClientMSG {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMSG) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ServerSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerSignal) Reset() {
	*x = ServerSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSignal) ProtoMessage() {}

func (x *ServerSignal) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSignal.ProtoReflect.Descriptor instead.
func (*ServerSignal) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{4}
}

type ServerRES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*ServerRES_Message
	//	*ServerRES_Signal
	Response isServerRES_Response `protobuf_oneof:"response"`
}

func (x *ServerRES) Reset() {
	*x = ServerRES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRES) ProtoMessage() {}

func (x *ServerRES) ProtoReflect() protoreflect.Message {
	mi := &file_plot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRES.ProtoReflect.Descriptor instead.
func (*ServerRES) Descriptor() ([]byte, []int) {
	return file_plot_proto_rawDescGZIP(), []int{5}
}

func (m *ServerRES) GetResponse() isServerRES_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ServerRES) GetMessage() *ServerMSG {
	if x, ok := x.GetResponse().(*ServerRES_Message); ok {
		return x.Message
	}
	return nil
}

func (x *ServerRES) GetSignal() *ServerSignal {
	if x, ok := x.GetResponse().(*ServerRES_Signal); ok {
		return x.Signal
	}
	return nil
}

type isServerRES_Response interface {
	isServerRES_Response()
}

type ServerRES_Message struct {
	Message *ServerMSG `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ServerRES_Signal struct {
	Signal *ServerSignal `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

func (*ServerRES_Message) isServerRES_Response() {}

func (*ServerRES_Signal) isServerRES_Response() {}

var File_plot_proto protoreflect.FileDescriptor

var file_plot_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x09,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x53, 0x47, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x22, 0x67, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x45, 0x51,
	0x12, 0x26, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x53, 0x47, 0x48, 0x00, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x09,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x53, 0x47, 0x12, 0x1c, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x53, 0x47, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22, 0x68, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x45, 0x53, 0x12, 0x26, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x53,
	0x47, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x06,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x2d, 0x0a, 0x07, 0x43, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x04,
	0x56, 0x6f, 0x49, 0x50, 0x12, 0x0a, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x45, 0x51,
	0x1a, 0x0a, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x45, 0x53, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plot_proto_rawDescOnce sync.Once
	file_plot_proto_rawDescData = file_plot_proto_rawDesc
)

func file_plot_proto_rawDescGZIP() []byte {
	file_plot_proto_rawDescOnce.Do(func() {
		file_plot_proto_rawDescData = protoimpl.X.CompressGZIP(file_plot_proto_rawDescData)
	})
	return file_plot_proto_rawDescData
}

var file_plot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plot_proto_goTypes = []interface{}{
	(*ClientMSG)(nil),    // 0: ClientMSG
	(*ClientSignal)(nil), // 1: ClientSignal
	(*ClientREQ)(nil),    // 2: ClientREQ
	(*ServerMSG)(nil),    // 3: ServerMSG
	(*ServerSignal)(nil), // 4: ServerSignal
	(*ServerRES)(nil),    // 5: ServerRES
}
var file_plot_proto_depIdxs = []int32{
	0, // 0: ClientREQ.message:type_name -> ClientMSG
	1, // 1: ClientREQ.signal:type_name -> ClientSignal
	0, // 2: ServerMSG.msg:type_name -> ClientMSG
	3, // 3: ServerRES.message:type_name -> ServerMSG
	4, // 4: ServerRES.signal:type_name -> ServerSignal
	2, // 5: Calling.VoIP:input_type -> ClientREQ
	5, // 6: Calling.VoIP:output_type -> ServerRES
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_plot_proto_init() }
func file_plot_proto_init() {
	if File_plot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMSG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientREQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMSG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_plot_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ClientREQ_Message)(nil),
		(*ClientREQ_Signal)(nil),
	}
	file_plot_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ServerRES_Message)(nil),
		(*ServerRES_Signal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plot_proto_goTypes,
		DependencyIndexes: file_plot_proto_depIdxs,
		MessageInfos:      file_plot_proto_msgTypes,
	}.Build()
	File_plot_proto = out.File
	file_plot_proto_rawDesc = nil
	file_plot_proto_goTypes = nil
	file_plot_proto_depIdxs = nil
}
